blog/urls.py
from django.urls import path
from .views import *

app_name = 'blog'

urlpatterns = [
    path('', post_list , name='post_list'),
    path('post/<int:pk>/', post_details , name='post_details'),
    path('post/new/', new_post , name='new_post'),
    path('post/<int:pk>/edit/', post_edit , name='post_edit'),
    path('post/<int:pk>/delete/', post_delete , name='post_delete'),
    path('post/<int:pk>/comment/', add_comment , name='add_comment'),
]

matrimony/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),   
    path('blog/', include('blog.urls')),   
    # password Change
    path('password_change/' , auth_views.PasswordChangeView.as_view() , name='password_change'), #as_view is used for class based views cuz passwordchangeview is django builtin vie which is class-based view
    path('password_change/done/' , auth_views.PasswordChangeDoneView.as_view() , name='password_change_done'), 
    #password Reset
    path('password_reset/' , auth_views.PasswordResetView.as_view() , name='password_reset'), 
    path('password_reset/done/' , auth_views.PasswordResetDoneView.as_view() , name='password_reset_done'), 
    path('reset/<uidb64>/<token>' , auth_views.PasswordResetConfirmView.as_view() , name='password_reset_confirm'), 
    path('reset/done/' , auth_views.PasswordResetCompleteView.as_view() , name='password_reset_complete'), 


    path('', include('profile_app.urls')),
    # static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT),

    # there is password manage process given below:

    # password_change
    # password_change_done

    # password_reset
    # password_reset_done
    # password_reset_confirm
    # password_reset_complete
]

# Serving media files during development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
# Create your models here.
    
class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL ,on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True , null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title
    
class Comment(models.Model):
    post = models.ForeignKey(Post , related_name='comments' , on_delete=models.CASCADE)
    author = models.ForeignKey(settings.AUTH_USER_MODEL ,on_delete=models.CASCADE)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.text
    

blog/forms.py
from django import forms
from .models import *

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title' , 'text',)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ( 'text',)

blog/views.py
from django.shortcuts import render , redirect , get_object_or_404
from .models import *
from django.utils import timezone
from .forms import *
from django.contrib.auth.decorators import login_required

# Create your views here.

def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')
    return render(request , 'blog/post_list.html' , {'posts': posts})

def post_details(request , pk):
    post = get_object_or_404(Post , pk=pk)
    comments = post.comments.all()
    return render(request , 'blog/post_details.html', {'post':post , 'comments':comments})
@login_required
def new_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        
        if form.is_valid():
            post=form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('blog:post_details' , pk=post.pk)
    else:
        form=PostForm()
    return render(request , 'blog/new_post.html' , {'form':form})

def post_edit(request , pk):
    post = get_object_or_404(Post , pk=pk)
    if request.method == 'POST':
        form = PostForm(request.POST , instance = post)
        if form.is_valid():
            post=form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('blog:post_details' , pk=post.pk)
    else:
         form=PostForm(instance = post)
    return render(request , 'blog/new_post.html' , {'form':form})

def post_delete(request , pk):
    post = get_object_or_404(Post , pk=pk)
    post.delete()
    return redirect('blog:post_list')

def add_comment(request ,pk):
    post = get_object_or_404(Post , pk=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment=form.save(commit=False)
            comment.post = post
            comment.author = request.user
            comment.save()
            return redirect('blog:post_details' , pk=post.pk)
    else:
        form=CommentForm()
    return render(request , 'blog/add_comment.html' , {'form':form})

blog/templates/blog/add_comment.html
{% extends "base.html" %}
{% block title %}Add Comment{% endblock title %}

{% block content %}
{% include "blog/blognav.html" %}
<h2>Add Comment</h2>
<form action="" method="post">
{% csrf_token %}
{{form.as_p}}
<button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock content %}

blog/templates/blog/blognav.html
<!-- Subnavbar -->
<nav class="navbar navbar-light">
    <ul class="nav">
      <li class="nav-item">
        <a class=" btn btn-primary mx-1 " href="{% url 'blog:post_list'%}">Your Blogs</a>
      </li>
      <li class="nav-item">
        <a class=" btn btn-primary" href="{% url 'blog:new_post'%}">Create a Blog</a>
      </li> 
    </ul>
  </nav>

blog/templates/blog/new_post.html
{% extends "base.html" %}
{% block title %}New Post{% endblock title %}

{% block content %}
{% include "blog/blognav.html" %}
<h4>{% if form.instance.pk %}Edit {% else %}New{% endif %}</h4>
<form action="" method="post">
{% csrf_token %}
{{form.as_p}}
<button type="submit" class="btn btn-primary">{% if form.instance.pk %}Update{% else %}Post{% endif %}</button>
</form>
{% endblock content %}

blog/templates/blog/post_details.html
{% extends "base.html" %}
{% block title %}Blog Detail{% endblock title %}

{% block content %}
{% include "blog/blognav.html" %}
<h2>{{post.title}}</h2>
<p>@{{post.author}} on {{post.published_date}}</p>
<p>{{post.text|safe}}</p>
<a href="{% url 'blog:post_delete' post.pk%}" class="btn btn-danger my-3">Delete Post</a>
<h4>Comments:</h4>
{% if comments %}
{% for comment in comments  %}
<div class="card mt-3">
    <div class="card-body">
        <h6 class="card-subtitle mb-2 text-muted">{{comment.author}} on {{comment.created_date}}</h6>
        <p class="card-text">{{comment.text}}</p>
    </div>
</div>
{% endfor %}
{% else %} 
<p class="text-muted">No Comments!</p>
{% endif %}
<a href="{% url 'blog:add_comment' post.pk%}" class="btn btn-primary mt-3">Add Comment</a>
{% endblock content %}

blog/templates/blog/post_list.html
{% extends "base.html" %}
{% block title %}All Blogs{% endblock title %}

{% block content %}
{% include "blog/blognav.html" %}
{% for post in posts  %}
<div class="card mt-3">
    <div class="card-body">
        <h5 class="card-title">{{post.title}}</h5>
        <h6 class="card-subtitle mb-2 text-muted">@{{post.author}}</h6>
        <p class="card-text">{{post.text|truncatewords:50|safe}}</p>
        <a href="{% url 'blog:post_details' post.pk%}" class="btn btn-primary">Read More</a>
    </div>
</div>
{% endfor %}
{% endblock content %}