accounts/urls.py
from django.urls import path
from .views import *

app_name = 'accounts'

urlpatterns = [
    path("login/", LoginView, name="login"),
    path("register/", RegisterView, name="register"),
    path("logout/", LogoutView, name="logout"),
    path("delete/", DeleteAccountView, name="delete_account"),
    path("verify_email/<str:token>/", verify_email_view, name="verify_email"),
]

blog/urls.py
from django.urls import path
from .views import *

app_name = 'blog'

urlpatterns = [
    path('', post_list , name='post_list'),
    path('post/<int:pk>/', post_details , name='post_details'),
    path('post/new/', new_post , name='new_post'),
    path('post/<int:pk>/edit/', post_edit , name='post_edit'),
    path('post/<int:pk>/delete/', post_delete , name='post_delete'),
    path('post/<int:pk>/comment/', add_comment , name='add_comment'),
]

matrimony/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),   
    path('blog/', include('blog.urls')),   
    # password Change
    path('password_change/' , auth_views.PasswordChangeView.as_view() , name='password_change'), #as_view is used for class based views cuz passwordchangeview is django builtin vie which is class-based view
    path('password_change/done/' , auth_views.PasswordChangeDoneView.as_view() , name='password_change_done'), 
    #password Reset
    path('password_reset/' , auth_views.PasswordResetView.as_view() , name='password_reset'), 
    path('password_reset/done/' , auth_views.PasswordResetDoneView.as_view() , name='password_reset_done'), 
    path('reset/<uidb64>/<token>' , auth_views.PasswordResetConfirmView.as_view() , name='password_reset_confirm'), 
    path('reset/done/' , auth_views.PasswordResetCompleteView.as_view() , name='password_reset_complete'), 


    path('', include('profile_app.urls')),
    # static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT),

    # there is password manage process given below:

    # password_change
    # password_change_done

    # password_reset
    # password_reset_done
    # password_reset_confirm
    # password_reset_complete
]

# Serving media files during development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profile_app/urls.py
from django.urls import path
from .views import *

app_name = 'profile_app'

urlpatterns = [
    path('' , profileListView , name= 'profile_list'),
    path('<int:profile_id>' , profileDetailView , name= 'profile_detail'),
    path('<int:profile_id>/delete' , profileDeleteView , name= 'profile_delete'),
    path('create/' , profileCreateView , name= 'profile_create'),
    path('contact/' , ContactFormView, name= 'contactform'),
    path('search/', profileSearchView, name='profile_search'),

]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'profile_app/css/style.css' %}">
</head>
<style>
    
</style>
<body>
    {% include "header.html" %}
    <main role="main" class="container content-page-height">
        {% block content %}

        {% endblock content %}
    </main>
    {% include "footer.html" %}
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>



</body>

</html>

templates/footer.html
<footer class="py-3 my-4">
    <p class="text-center text-muted">© 2023 Company, Inc</p>
  </footer>

templates/header.html
<header class="p-3 bg-dark text-white">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
          <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
        </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><a href="{% url 'profile_app:profile_list'%}" class="nav-link px-2 text-secondary">Home</a></li>
          <li><a href="{% url 'profile_app:profile_create'%}" class="nav-link px-2 text-white">Create Profile</a></li>
          <li><a href="{% url 'blog:post_list'%}" class="nav-link px-2 text-white">Blogs</a></li>
          <li><a href="{% url 'profile_app:contactform'%}" class="nav-link px-2 text-white">Contact Us</a></li>
        </ul>

        <form action="{% url 'profile_app:profile_search' %}" method="get" class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
          <input type="search" name="search_query" class="form-control form-control-dark" placeholder="Search..." aria-label="Search">
      </form>
      

        <div class="text-end">
          {% if user.is_authenticated %}
          <div class="d-flex align-items-center">

            <div  class="dropdown">
              <button class="btn text-white dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                Hi, {{ user.username }}
              </button>
              <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                <li><a class="dropdown-item" href="{% url 'password_change'%}" >Change password</a></li>
                <li><a class="dropdown-item" href="{% url 'accounts:delete_account'%}" >Delete account</a></li>
                <li><a class="dropdown-item" href="{% url 'accounts:logout' %}" >Logout</a></li>
              </ul>
            </div>
          
          {% else %}
              <a href="{% url 'accounts:login' %}" class="btn btn-outline-light me-2">Login</a>
              <a href="{% url 'accounts:register' %}" class="btn btn btn-warning">Register</a>
          {% endif %}

        </div>
      </div>
    </div>
  </header>