blog/urls.py
from django.urls import path
from .views import *

app_name = 'blog'

urlpatterns = [
    path('', post_list , name='post_list'),
    path('post/<int:pk>/', post_details , name='post_details'),
    path('post/new/', new_post , name='new_post'),
    path('post/<int:pk>/edit/', post_edit , name='post_edit'),
    path('post/<int:pk>/delete/', post_delete , name='post_delete'),
    path('post/<int:pk>/comment/', add_comment , name='add_comment'),
]

matrimony/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),   
    path('blog/', include('blog.urls')),   
    # password Change
    path('password_change/' , auth_views.PasswordChangeView.as_view() , name='password_change'), #as_view is used for class based views cuz passwordchangeview is django builtin vie which is class-based view
    path('password_change/done/' , auth_views.PasswordChangeDoneView.as_view() , name='password_change_done'), 
    #password Reset
    path('password_reset/' , auth_views.PasswordResetView.as_view() , name='password_reset'), 
    path('password_reset/done/' , auth_views.PasswordResetDoneView.as_view() , name='password_reset_done'), 
    path('reset/<uidb64>/<token>' , auth_views.PasswordResetConfirmView.as_view() , name='password_reset_confirm'), 
    path('reset/done/' , auth_views.PasswordResetCompleteView.as_view() , name='password_reset_complete'), 


    path('', include('profile_app.urls')),
    # static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT),

    # there is password manage process given below:

    # password_change
    # password_change_done

    # password_reset
    # password_reset_done
    # password_reset_confirm
    # password_reset_complete
]

# Serving media files during development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profile_app/urls.py
from django.urls import path
from .views import *

app_name = 'profile_app'

urlpatterns = [
    path('' , profileListView , name= 'profile_list'),
    path('<int:profile_id>' , profileDetailView , name= 'profile_detail'),
    path('<int:profile_id>/delete' , profileDeleteView , name= 'profile_delete'),
    path('create/' , profileCreateView , name= 'profile_create'),
    path('contact/' , ContactFormView, name= 'contactform'),
    path('search/', profileSearchView, name='profile_search'),

]

profile_app/models.py
from django.db import models
from django.core.files.storage import FileSystemStorage
from django.conf import settings
fs = FileSystemStorage(location=settings.MEDIA_ROOT)

# Create your models here.
class Religion(models.Model):
   name = models.CharField(max_length=100)

   def __str__(self):
       return self.name
   
class Sect(models.Model):
   name = models.CharField(max_length=100)
   religion = models.ForeignKey(Religion, on_delete=models.CASCADE, related_name='sects')

   def __str__(self):
       return self.name

class Caste(models.Model):
   name = models.CharField(max_length=100)

   def __str__(self):
       return self.name

class Hobby(models.Model):
   name = models.CharField(max_length=100)

   class Meta:
    verbose_name_plural = 'Hobbies'
   def __str__(self):
       return self.name 

class FatherProfile(models.Model):
   name = models.CharField(max_length=100)
   occupation = models.CharField(max_length=100 , null=True , blank=True)

   def __str__(self):
       return self.name
   
class profile(models.Model):
    GENDER_CHOICE = [
        ('Male' , 'M'),
        ('Female' , 'F')
    ]
    name = models.CharField(max_length=30)
    age = models.IntegerField()
    profile_pic = models.ImageField(upload_to='profile_pics/',null=True , blank=True)
    gender = models.CharField(max_length=10 , choices=GENDER_CHOICE)
    occupation = models.CharField(max_length=100 , null=True , blank=True)
    birth_date = models.DateField(null=True)
    is_married = models.BooleanField(default=False)
    email = models.EmailField(null=True , unique=True)

    religion = models.ForeignKey(Religion, on_delete=models.CASCADE  , related_name='profiles' , blank=True,null=True)
    sects = models.ForeignKey(Sect, on_delete=models.CASCADE ,  related_name='Followers' , blank=True, null=True)
    caste = models.ForeignKey(Caste, on_delete=models.CASCADE , related_name='profiles' , blank=True, null=True)
    hobbies = models.ManyToManyField(Hobby , related_name='profiles' , blank=True)
    father = models.OneToOneField(FatherProfile , on_delete=models.CASCADE , related_name='dependent' , blank=True, null=True)

    def save(self, *args, **kwargs):
       print(f'data updated for {self.name}')
       super().save(*args, **kwargs) # Call the real save() method

    def __str__(self):
      return self.name

profile_app/forms.py
from typing import Any
from django import forms
from django.core.validators import EmailValidator
from django.core.exceptions import ValidationError
from .models import profile



class NewProfileForm(forms.ModelForm):
    class Meta:
        model = profile
        fields = "__all__"
        # fields = ["name" , 'age' .....] // this for specific field to put
        # exclude = ["name" , 'age' .....]  // mean exclude this fields from form but others all are shown

    is_married = forms.BooleanField(
        label="Status",  # Change the label here
        required=False  # Add other attributes as needed
    )   




def my_email_validator(email):
    if email.split('@')[1].split('.')[0].lower()=='hotmail':
        raise ValidationError("Email not accepatable")

class contactForm(forms.Form):
    name = forms.CharField(max_length=50)
    email = forms.CharField(validators=[EmailValidator() , my_email_validator])
    verify_email = forms.CharField(validators=[EmailValidator()])
    message = forms.CharField(widget=forms.Textarea)   
    
    def clean(self):
        cleaned_data= super().clean()

        name = cleaned_data.get('name')
        email = cleaned_data.get('email').lower()
        verify_email = cleaned_data.get('verify_email').lower()
        message = cleaned_data.get('message')

        cleaned_data['email'] = email
        cleaned_data['verify_email'] = verify_email

        if email != verify_email:
            raise ValidationError("Email Mismatch")
        return cleaned_data

class ProfileSearchForm(forms.Form):
    search_query = forms.CharField(max_length=100, required=False)

profile_app/views.py
from django.shortcuts import render , redirect
from django.http import HttpResponse
from .models import *
from django.urls import reverse
from .forms import *
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User


# Create your views here.

def profileListView(request):
    profiles = profile.objects.all()
    user = request.user
    return render( request , 'profile_app/profile_list.html' , {'profiles' : profiles ,'user':user}) 

def profileDetailView(request , profile_id):
    Profile = profile.objects.get(id=profile_id)
    user = request.user
    return render( request , 'profile_app/profile_details.html', {'Profile' : Profile ,'user':user}) 

def profileDeleteView(request , profile_id):
    Profile_delete = profile.objects.get(id=profile_id)
    Profile_delete.delete()
    # profiles = profile.objects.all()
    return redirect(reverse('profile_app:profile_list'))
    # return render( request , 'profile_app/profile_list.html' , {'profiles' : profiles}) 
    
@login_required
def profileCreateView(request):
    if request.method == 'POST':
        form = NewProfileForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()  # Save the form data to create a new profile
            return redirect(reverse('profile_app:profile_list'))
    else:
        form = NewProfileForm()
    return render(request, 'profile_app/form.html', {'form': form})





def ContactFormView(request):
    if request.method =='POST':
        form = contactForm(request.POST)
        if form.is_valid():
            print(f"NAME:{form.cleaned_data['name']}")
            print(f"EMAIL:{form.cleaned_data['email']}")
            print(f"MESSAGE:{form.cleaned_data['message']}")
    else:
        form = contactForm()    
    return render( request , 'profile_app/contactForm.html' , {'form':form}) 

def profileSearchView(request):
    search_query = request.GET.get('search_query', '')
    
    if search_query:
        profiles = profile.objects.filter(name__icontains=search_query)
        template_name = 'profile_app/profile_search_results.html'
    else:
        profiles = profile.objects.all()
        template_name = 'profile_app/profile_list.html'
    
    return render(request, template_name, {'profiles': profiles, 'search_query': search_query})

profile_app/templates/profile_app/contactForm.html
{% extends "base.html" %}
{% block title %}Contact Form{% endblock title %}
{% block content %}
<form  method="post">
    {% csrf_token %}
    <div class="form-group m-4">
        {{form.name.label_tag}}
        <input type="text" class="form-control" name="{{form.name.name}}">
    </div>

    <div class="form-group m-4">
        {{form.email.label_tag}}
        <input type="email" class="form-control" name="{{form.email.name}}">
    </div>
    <div class="form-group m-4">
        {{form.verify_email.label_tag}}
        <input type="email" class="form-control" name="{{form.verify_email.name}}">
    </div>
    <div class="form-group m-4">
        {{form.message.label_tag}}
        <textarea class="form-control" name="{{form.message.name}}" rows="3"></textarea>
    </div>

    <button type="submit" class="btn btn-primary m-4">Submit</button>

</form>
</form>
{% endblock content %}

profile_app/templates/profile_app/form.html
{% extends "base.html" %}
{% block title %}Form{% endblock title %}
{% block content %}
<form  method="post"  enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit" class="btn btn-primary">Submit</button>
  {% comment %} <div class="row my-3">
    <div class="col">
      {{form.name.label_tag}}
      <input type="text" class="form-control" name = {{form.name.name}} placeholder="Your name">
    </div>
    <div class="col">
      {{form.age.label_tag}}
      <input type="number" class="form-control" name = {{form.age.name}} placeholder="Your age">
    </div>
  </div>

  <div class="row my-3">
    <div class="col">
      {{form.father.label_tag}}
      <input type="text" class="form-control" name = {{form.father.name}} placeholder="Father's name">
    </div>
    <div class="col">
      {{form.occupation.label_tag}}
      <input type="text" class="form-control" name = {{form.occupation.name}} placeholder="Father's occupation">
    </div>
  </div>

  <div class="row my-3">
    <div class="col">
      {{form.email.label_tag}}
      <input type="email" class="form-control" name = {{form.email.name}} placeholder="Your email">
    </div>
    <div class="col">
      {{form.birth_date.label_tag}}
      <input type="date" class="form-control" name = {{form.birth_date.name}} placeholder="Your DOB">
    </div>
  </div>

  <div class="row my-3">
    <div class="col">
      {{form.profile_pic.label_tag}}
      <input type="file" class="form-control" name = {{form.profile_pic.name}} placeholder="Choose Your Profile">
    </div>
  </div>

  <div class="row my-3">
    <div class="col">
      {{form.gender.label_tag}}
      <select class="form-select" name="{{ form.gender.name }}">
        {% for choice in form.gender.field.choices %}
          <option value="{{ choice.0 }}">{{ choice.1 }}</option>
        {% endfor %}
      </select>
    </div>
    <div class="col">
      {{ form.religion.label_tag }}
      <select class="form-select" name="{{ form.religion.name }}">
        {% for religion in form.religion.field.choices %}
          <option value="{{ religion.0 }}">{{ religion.1 }}</option>
        {% endfor %}
      </select>
    </div>
    <div class="col">
      {{ form.sects.label_tag }}
      <select class="form-select" name="{{ form.sects.name }}">
        {% for sect in form.sects.field.choices %}
          <option value="{{ sect.0 }}">{{ sect.1 }}</option>
        {% endfor %}
      </select>
    </div>
  </div>

  <div class="row my-3">
    <div class="col">
      {{ form.hobbies.label_tag }}
      <div class="form-check">
        {% for hobby in form.hobbies.field.choices %}
          <input class="form-check-input" type="checkbox" name="{{ form.hobbies.name }}" value="{{ hobby.0 }}">
          <label class="form-check-label" for="{{ form.hobbies.name }}_{{ hobby.0 }}">{{ hobby.1 }}</label><br>
        {% endfor %}
    </div>
    <div class="col">
      {{form.is_married.label}}
      <div class="form-check">
        <input class="form-check-input" type="checkbox" id="married_check" name="form.is_married.name">
        <label class="form-check-label" for="married_check">
        Married
        </label>
      </div>
    </div>
  </div>


    <div class="col-12">
      <button type="submit" class="btn btn-primary">Submit</button>
    </div> {% endcomment %}
</form>
{% endblock content %}

profile_app/templates/profile_app/profile_details.html
{% extends "base.html" %}
{% block title %}Profile Details{% endblock title %}
{% block content %}
 <!-- <h1>This is profile of {{Profile.name}}</h1> -->
 <div class="header_img">
    <div class="image">
        <img src="{{Profile.profile_pic.url}}" alt="profile_image">
    </div>
</div>

<div class="info">
    <ul>
        <li><span>Name</span> : {{Profile.name}}</li>
        <li><span>Age</span> : {{Profile.age}}</li>
        <li><span>Gender</span> : {{Profile.gender}}</li>
        <li><span>Email</span> : {{Profile.email}}</li>
        <li><span>Occupation</span> : {{Profile.occupation}}</li>
        <li><span>DOB</span> : {{Profile.birth_date}}</li>
        <li><span>Married Status</span> : 
            {% if Profile.is_married %}
                Married
            {% else %}
                Not Married
            {% endif %}
        </li>
        <li><span>Father Name</span> : {{Profile.father.name}}</li>
        <li><span>Father Occupation</span> : {{Profile.father.occupation}}</li>
        <li><span>Religion</span> : {{ profile.religion.name}}<li><span>Sects</span> :
        {% for sect in Profile.sects.all %}
            {{ sect.name }}
        {% endfor %}
        </li>
        <li><span>Caste</span> :
        {% for caste in Profile.caste.all %}
            {{ caste.name }}
        {% endfor %}
        </li>
        <li><span>Hobbies</span> :      
            {% for hobby in Profile.hobbies.all  %}
            {{hobby}}
            {% endfor %}
            </ul>    
        </li>
    </ul>
    
    <div class="d-grid gap-2 container">
        <a class="btn btn-danger" href="{% url 'profile_app:profile_delete' Profile.id%}" role="button">Delete</a>
        <a class="btn btn-primary" href="{% url 'profile_app:profile_list'%}" role="button">Back</a>
      </div>
</div>
{% endblock content %}

profile_app/templates/profile_app/profile_list.html
{% extends "base.html" %}
{% block title %}Profile List{% endblock title %}
{% block content %}
<h1 class="m-5">Profile of Users</h1>
   {% if profiles %}
      <div class="row">
        {% for profile in profiles %}
            <div class="col-md-4" >
                <div class="card d-flex" style="width: 18rem; height: 100%; ">
                    {% if profile.profile_pic %}
                    <img src="{{ profile.profile_pic.url }}" alt="profile_image">
                {% else %}
                    <p>No profile picture available</p>
                {% endif %}
                    <div class="card-body">
                      <h5 class="card-title">{{profile.name}}</h5>
                      <a href="{% url 'profile_app:profile_detail' profile.id %}" class="btn btn-primary">Profile Details</a>
                    </div>
                  </div>
            </div>
        {% endfor %}
      </div>
   {% endif %}
{% endblock content %}


    {% comment %} {% block content %}
    <h1>This is profile lists</h1>

    {% if profiles %}
    <ul>
        {% for profile in profiles %}
        <div class="profile">
            <div class="image">
                <img src=" {{profile.profile_pic.url}}" alt="Profile_Image">
            </div>
            <div class="name">
                <a href="{% url 'profile_app:profile_detail' profile.name %}">{{profile.name}}</a>
            </div>
        </div>
        {% endfor %}
    </ul>
    {% endif %}
    {% endblock content %} {% endcomment %}

profile_app/templates/profile_app/profile_search_results.html
{% extends "base.html" %}
{% block title %}Search Results{% endblock title %}
{% block content %}
    <h1 class="m-5">Search Results for "{{ search_query }}"</h1>
    {% if profiles %}
        <div class="row">
            {% for profile in profiles %}
            <div class="col-md-4" >
                <div class="card d-flex" style="width: 18rem; height: 100%; ">
                    {% if profile.profile_pic %}
                    <img src="{{ profile.profile_pic.url }}" alt="profile_image">
                {% else %}
                    <p>No profile picture available</p>
                {% endif %}
                    <div class="card-body">
                      <h5 class="card-title">{{profile.name}}</h5>
                      <a href="{% url 'profile_app:profile_detail' profile.id %}" class="btn btn-primary">Profile Details</a>
                    </div>
                  </div>
            </div>
            {% endfor %}
        </div>
    {% else %}
        <p>No profiles found for "{{ search_query }}".</p>
    {% endif %}
{% endblock content %}